import React,{useState,useEffect}from'react';
import{View,Text,StyleSheet,TextInput,Pressable,Alert,ActivityIndicator}from'react-native';
import{COLORS}from'../theme/theme';import{NavScreen}from'../types';import{requestOtp,verifyOtp}from'../api/tourApi';
import{showApiError}from'../utils/toast';
interface Props{onLoginSuccess:(phone:string)=>void;onSkip:()=>void;onNavigate:(screen:NavScreen)=>void}
export const AuthScreen:React.FC<Props>=({onLoginSuccess,onSkip,onNavigate})=>{const[mobile,setMobile]=useState('');const[otpSent,setOtpSent]=useState(false);const[otp,setOtp]=useState('');const[timer,setTimer]=useState(30);const[loading,setLoading]=useState(false);
useEffect(()=>{if(!otpSent||timer<=0)return;const id=setInterval(()=>setTimer(t=>t-1),1000);return()=>clearInterval(id)},[otpSent,timer]);
const send=async()=>{if(mobile.replace(/\D/g,'').length<10){Alert.alert('Invalid number','Enter a valid mobile number.');return}setLoading(true);try{await requestOtp(mobile);setOtpSent(true);setTimer(30);Alert.alert('OTP sent','Check your phone for the verification code.')}catch(e:any){showApiError(e,'We could not send the OTP.')}finally{setLoading(false)}};
const verify=async()=>{if(otp.length<4){Alert.alert('Incomplete OTP','Enter the 4-digit OTP.');return}setLoading(true);try{await verifyOtp(mobile,otp);onLoginSuccess(mobile);onNavigate('home')}catch(e:any){showApiError(e,'The OTP could not be verified.')}finally{setLoading(false)}};
return <View style={s.container}><View style={s.top}><Pressable onPress={onSkip}><Text style={s.link}>← Back</Text></Pressable><Pressable onPress={onSkip}><Text style={s.gold}>Continue as Guest ›</Text></Pressable></View><View style={s.content}><Text style={s.icon}>👤</Text><Text style={s.title}>Login / Register</Text><Text style={s.subtitle}>Sign in to track enquiries and access your travel profile.</Text><View style={s.card}><Text style={s.label}>MOBILE NUMBER</Text><View style={s.row}><Text style={s.code}>+91</Text><TextInput style={s.input} value={mobile} onChangeText={setMobile} placeholder="10-digit mobile number" keyboardType="phone-pad" maxLength={10} editable={!otpSent}/></View>{otpSent&&<><Text style={s.label}>OTP</Text><TextInput style={s.input} value={otp} onChangeText={setOtp} placeholder="Enter 4-digit OTP" keyboardType="number-pad" maxLength={4}/><View style={s.timer}><Text>{timer?'Resend in '+timer+'s':''}</Text><Pressable onPress={()=>{setOtpSent(false);setOtp('')}}><Text style={s.link}>Change number</Text></Pressable></View></>}<Pressable style={s.button} onPress={otpSent?verify:send} disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{otpSent?'VERIFY & LOGIN →':'SEND OTP →'}</Text>}</Pressable></View></View></View>};
const s=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.bg},top:{flexDirection:'row',justifyContent:'space-between',padding:16,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:COLORS.border},content:{padding:20,alignItems:'center'},icon:{fontSize:38,marginTop:20},title:{fontSize:24,fontWeight:'900',color:COLORS.text,marginTop:12},subtitle:{textAlign:'center',color:COLORS.textSecondary,marginVertical:12},card:{width:'100%',backgroundColor:'#fff',padding:20,borderRadius:14,borderWidth:1,borderColor:COLORS.border},label:{fontSize:10,fontWeight:'800',color:COLORS.textSecondary,marginBottom:8,marginTop:8},row:{flexDirection:'row',gap:8,marginBottom:8},code:{padding:14,backgroundColor:COLORS.surface,borderRadius:8,fontWeight:'700'},input:{flex:1,borderWidth:1,borderColor:COLORS.border,borderRadius:8,padding:12,color:COLORS.text},button:{backgroundColor:COLORS.primary,padding:14,borderRadius:8,alignItems:'center',marginTop:16},buttonText:{color:'#fff',fontWeight:'800'},timer:{flexDirection:'row',justifyContent:'space-between',marginTop:8},link:{color:COLORS.primary,fontWeight:'700'},gold:{color:COLORS.goldDark,fontWeight:'700'}});
