import React from 'react';
import {ScrollView, StyleSheet, Text, View} from 'react-native';
import {COLORS} from '../theme/theme';
import {EnquiryData} from '../types';

const EmptyPage = ({icon, title, message}:{icon:string;title:string;message:string}) => <ScrollView style={styles.container} contentContainerStyle={styles.center}><View style={styles.icon}><Text style={styles.iconText}>{icon}</Text></View><Text style={styles.title}>{title}</Text><Text style={styles.message}>{message}</Text></ScrollView>;

export const MyTripsScreen = () => <EmptyPage icon="✈" title="My trips" message="Your confirmed and upcoming trips will appear here." />;

export const BillsInvoicesScreen = () => <EmptyPage icon="₹" title="Bills & invoices" message="Your booking bills and invoices will appear here once a booking is confirmed." />;

export const MyEnquiriesScreen: React.FC<{enquiries: EnquiryData[]}> = ({enquiries}) => <ScrollView style={styles.container} contentContainerStyle={styles.content}><Text style={styles.pageTitle}>My enquiries</Text>{enquiries.length === 0 ? <View style={styles.emptyBox}><Text style={styles.emptyTitle}>No enquiries yet</Text><Text style={styles.message}>Your tour enquiries and their latest status will appear here.</Text></View> : enquiries.map((item,index) => <View style={styles.enquiry} key={item.id || String(index)}><View style={styles.row}><Text style={styles.enquiryTitle}>{item.tourTitle || item.destination || 'Custom tour'}</Text><Text style={styles.status}>{item.status || 'PENDING'}</Text></View><Text style={styles.meta}>Travel date: {item.travelDate || 'Not selected'}</Text><Text style={styles.meta}>Mobile: {item.mobile}</Text>{item.id && <Text style={styles.ref}>Reference: {item.id}</Text>}</View>)}</ScrollView>;

const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.bg},content:{padding:16},center:{alignItems:'center',justifyContent:'center',padding:30},icon:{width:72,height:72,borderRadius:36,backgroundColor:COLORS.primarySubtle,alignItems:'center',justifyContent:'center',marginBottom:16},iconText:{fontSize:32,color:COLORS.primary},title:{fontSize:23,fontWeight:'900',color:COLORS.text},pageTitle:{fontSize:23,fontWeight:'900',color:COLORS.text,marginBottom:16},message:{fontSize:13,lineHeight:20,color:COLORS.textSecondary,textAlign:'center',marginTop:8},emptyBox:{backgroundColor:'#fff',borderRadius:15,borderWidth:1,borderColor:COLORS.border,padding:22,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800',color:COLORS.text},enquiry:{backgroundColor:'#fff',borderRadius:13,borderWidth:1,borderColor:COLORS.border,padding:15,marginBottom:10},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},enquiryTitle:{flex:1,fontSize:14,fontWeight:'800',color:COLORS.text},status:{fontSize:10,fontWeight:'800',color:COLORS.goldDark,backgroundColor:'#FEF3C7',paddingHorizontal:8,paddingVertical:4,borderRadius:6},meta:{fontSize:12,color:COLORS.textSecondary,marginTop:7},ref:{fontSize:10,color:COLORS.textMuted,marginTop:8}});
